
# YML file is just created for learning purpose . Go to READ_ME to unserdtand more


# spring :
#     security :
#         user :
#             name : username
#             password : password

# Above configuration is done for the specific user but in our current project 
# we want that all the users who sognUP are able to login. So , we will configure accordingly.
# to do the changes we need to configure the requirement using java code for that config folder is created.

# OAuth2 config : 

# Google configuration 
spring :
    security :
        OAuth2 :
            Client :
                registration :
                            google :
                                client-name : google
                                client-id : ${GOOGLE_CLIENT_ID}
                                client-secret : ${GOOGLE_CLIENT_SECRET}


# Git Hub Configuration :


# facebook configuration :